---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: newapp
  labels:
    app: newapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: newapp
  # pod spec begins here
  template:
    metadata:
      labels:
        app: newapp
    spec:
      containers:
        - name: newapp
          image: registry.digitalocean.com/golvachi-doreg/flask-kube:0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8888

